name: gha-tests

on:
  - push
  - pull_request

jobs:
  test:
    # Specify the environment to run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']  # Test against multiple Python versions, should correspond to requires-python in pyproject.toml

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      # Step 4: Run pytest
      - name: Run tests with pytest
        run: |
          pytest